<?php
/**
 * This is file was generated by the Magento Toolbox extension.
 * Foo_Bob is the name of the module.
 * 
 */
declare(strict_types=1);

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Foo_Bar', __DIR__);
