import FileHeader from 'common/php/FileHeader';
import GeneratedFile from 'generator/GeneratedFile';
import ModuleFileGenerator from 'generator/ModuleFileGenerator';
import { PhpFile, PsrPrinter } from 'node-php-generator';
import { Uri } from 'vscode';
import { BlockWizardData } from 'wizard/BlockWizard';

/**
 * This is file was generated by the Magento Toolbox extension.
 * %module% is the name of the module.
 */

export default class BlockClassGenerator extends ModuleFileGenerator {
  private static readonly BLOCK_CLASS_PARENT = 'Magento\\Framework\\View\\Element\\Template';

  public constructor(protected data: BlockWizardData) {
    super();
  }

  public async generate(workspaceUri: Uri): Promise<GeneratedFile> {
    const [vendor, module] = this.data.module.split('_');
    const namespaceParts = [vendor, module, this.data.path];
    const moduleDirectory = this.getModuleDirectory(vendor, module, workspaceUri);

    const header = FileHeader.getHeader(this.data.module);

    const phpFile = new PhpFile();
    if (header) {
      phpFile.addComment(header);
    }
    phpFile.setStrictTypes(true);

    const namespace = phpFile.addNamespace(namespaceParts.join('\\'));
    namespace.addUse(BlockClassGenerator.BLOCK_CLASS_PARENT);

    const blockClass = namespace.addClass(this.data.name);

    blockClass.setExtends(BlockClassGenerator.BLOCK_CLASS_PARENT);

    const printer = new PsrPrinter();

    return new GeneratedFile(
      Uri.joinPath(moduleDirectory, this.data.path, `${this.data.name}.php`),
      printer.printFile(phpFile)
    );
  }
}
